# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='data',
  syntax='proto3',
  serialized_pb=_b('\n\ndata.proto\x12\x04\x64\x61ta\"\x1c\n\x0c\x44\x61taResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1d\n\nDataReplay\x12\x0f\n\x07message\x18\x01 \x01(\t2@\n\nFormatData\x12\x32\n\x08\x44oFormat\x12\x12.data.DataResponse\x1a\x10.data.DataReplay\"\x00\x62\x06proto3')
)




_DATARESPONSE = _descriptor.Descriptor(
  name='DataResponse',
  full_name='data.DataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='data.DataResponse.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=48,
)


_DATAREPLAY = _descriptor.Descriptor(
  name='DataReplay',
  full_name='data.DataReplay',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='data.DataReplay.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['DataResponse'] = _DATARESPONSE
DESCRIPTOR.message_types_by_name['DataReplay'] = _DATAREPLAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataResponse = _reflection.GeneratedProtocolMessageType('DataResponse', (_message.Message,), dict(
  DESCRIPTOR = _DATARESPONSE,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:data.DataResponse)
  ))
_sym_db.RegisterMessage(DataResponse)

DataReplay = _reflection.GeneratedProtocolMessageType('DataReplay', (_message.Message,), dict(
  DESCRIPTOR = _DATAREPLAY,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:data.DataReplay)
  ))
_sym_db.RegisterMessage(DataReplay)



_FORMATDATA = _descriptor.ServiceDescriptor(
  name='FormatData',
  full_name='data.FormatData',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=81,
  serialized_end=145,
  methods=[
  _descriptor.MethodDescriptor(
    name='DoFormat',
    full_name='data.FormatData.DoFormat',
    index=0,
    containing_service=None,
    input_type=_DATARESPONSE,
    output_type=_DATAREPLAY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FORMATDATA)

DESCRIPTOR.services_by_name['FormatData'] = _FORMATDATA

# @@protoc_insertion_point(module_scope)
